heroku/heroku-cli-util

lib/styled.js, test/styled.js
I messed up logKeyValue when rewriting it. Fixed now.
=> Fix logKeyValue padding

lib/action.js, lib/console.js
Add cli.writeError and make cli.action use it.
=> Make cli.action mockable

README.md, index.js, lib/table.js, package.json, test/table.js, test/util.js
thoughts @bjeanes? It's a direct port from your code
=> added table

lib/console.js
Only show hush messages if HEROKU_DEBUG is set to 1 or true.
Also moved the output to stderr.
cc @rbriggs
=> hush changes

lib/styled.js, package.json, test/styled.js
this made it impossible to have titles like HEROKU_CONFIG
=> remove titleize on styledObject

lib/table.js
=> do not error if value is null

lib/errors.js, test/errors.js
otherwise only color differentiates from errors
thoughts @ransombriggs?
=> prepend warnings with WARNING:

lib/command.js, package.json
depends on https://github.com/heroku/node-heroku-client/pull/55
=> show api warning

lib/spinner.js, test/spinner.js
cc @dzuelke 
Fixes https://github.com/heroku/heroku/issues/1931
=> fix spinner with narrow screens

index.js, lib/exit.js
=> Add exit.js extracted from heroku-certs

README.md
=> Remove old proxy style from README

lib/exit.js
This adjusts the exit.mock function to be more like the other mocked functions
=> adjustable exit mocking

test/got.js
@dickeyxxx review me?  this a fix for the test breakage in https://github.com/heroku/heroku-cli-util/pull/81 technically master is broke too, we just have noticed because it has been a while since anyone pushed anything.  In order to recreate locally I had to hose my `node_modules` to replicate the test environment.
=> Fix confusing got test break breakage

lib/login.js, test/login.js
=> Add sso login option to login()

lib/prompt.js, test/prompt.js
=> Throw error when not tty and prompt masked

lib/command.js, test/command.js
@dickeyxxx could you review?  I had to do some gross stuff to make this work, plus the tests around this take an abnormally long time, which is making me a little nervous.  Do not release this yet, just wanted feedback.  If you are good with it, I will wait until next Thursday to bump everything and release (I am out this afternoon through Thursday)
=> Retry just the request when 2fa / preauth

lib/command.js
Fixes https://github.com/heroku/cli-engine/issues/29
=> return promises to keep command alive

lib/errors.js
Fixes https://github.com/heroku/cli/issues/527
=> move cache dir on macos

yarn.lock
Various security updates. This will not require a deployment.
=> Updated vulnerable deps

README.md, package-lock.json, package.json, src/index.ts, src/ux/styled-json.ts, src/ux/table.ts, test/unit/ux/styled-json.test.ts
[W-18293330](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CtebTYAR/view)
This fixes the table implementation and corrects the ux exports
=> fix: fix a few ux exports

package-lock.json, package.json
Relase PR for version 10.1.1 (for upcoming Core CLI v11) with changes to `tunnel-ssh`.
GUS Work Item: [W-19689442](https://gus.lightning.force.com/a07EE00002M33k2YAB)
N/A
=> Release v10.1.1 (W-19689442)
