.gitignore, cli.js
exposes the console so plugins can use `mock` in their tests too:
```js
var cli = require('heroku-cli-util');
cli.console.mock();
// plugin tests here will be able to inspect stdout/stderr without invading test results
```
=> expose console on cli object

cli.js
@dickeyxxx `errors` already closes over console, but I missed it on `log`
=> bind exposed console

lib/styled.js
current:
dull header:
dull equals + bold header:
Another example:
=> variations on a header

lib/console.js
> cli.log(undefined, undefined)
undefined undefined
> cli.mockConsole()
> cli.log(undefined, undefined)
> cli.stdout
'undefined,undefined\n'
=> Fixing join character in mock from , to space

lib/table.js
This won't visibly change the output but it will remove trailing spaces
at the end of the table output. These spaces throw off `wc` numbers and
require adding trailing spaces to some of the tests.
=> trim table trailing spaces

lib/styled.js, test/styled.js
nearly all the DoD plugins want to use this kind of output. Using
styledHash and converting from the format here works somewhat ok,
buuuuut breaks down if you want to e.g. have duplicate keys.
For example, here's the current (broken) output of `heroku
cassandra:info`:
```bash
=== CASSANDRA_URL
Name:        cassandra-hi-jeff-5562
Created:     2015-09-42 09:42 UTC
Plan:        Alpha Medium
Status:      available
Connections: 368
Tables:      9001
Data Size:   1.35 PB
== Reads:
Throughput:  849.37
Latency:     50th 0.24ms
95th 0.24ms
99th 0.92ms
== Writes:
Throughput:  849.37
Latency:     50th 0.24ms
95th 0.24ms
99th 0.92ms
```
The duplicated "throughput" and latency columns happen because `styledHash`
doesn't allow for keys with the same name.
=> add styled name values

circle.yml, lib/errors.js, test/errors.js
this has been getting in the way more than it has been helping. For
example, cli.confirmApp() is pretty broken looking because of it.
I still don't like that without colors warnings look like errors, but
we'll have to find a different solution to that problem.
For example:
```
$ heroku redis:cli -a heroku-npm
▸    WARNING: WARNING: Insecure action.
▸    All data, including the Redis password, will not be encrypted.
▸    WARNING: To proceed, type heroku-npm or re-run this command with --confirm heroku-npm
```
=> remove prepending warnings with WARNING:

lib/errors.js
turns this:
```
▸    To drain to splunk do the following:
▸    $ heroku drains:add -a heroku-npm https://$(foo > /dev/null; foo-client
▸    MAP | awk -F '|' {print
▸    $2}')@logs.foo.com/logs
```
into this:
```
▸    To drain to splunk do the following:
▸    $ heroku drains:add -a heroku-npm https://$(foo > /dev/null; foo-client MAP | awk -F '|' {print $2}')@logs.foo.com/logs
```
=> fix wrapping with command examples

lib/rollbar.js
This fixes a bug where the rollbar client does not properly use the HTTPS_PROXY variables
=> Replace rollbar https client with got client

README.md
This wasn't clear to me and [I broke --confirm in our Kafka plugin](https://github.com/heroku/heroku-kafka-jsplugin/pull/67).
=> Note that cli.confirmApp needs a confirm flag

index.js, lib/prompt.js
For tests, results get really noisy when prompts output every time. Instead of messing with stderr (also, why does `cli.prompt` use stderr?), adding an option seems like a more straightforward solution.
=> add quiet mode for cli.prompt

lib/color.js
I was updating the [heroku-pipelines](https://github.com/heroku/heroku-pipelines) to make use of the standard color definition for apps, and then I realized that instead of coming with a color to also indicate pipelines, it'd be nice to standardize it in case other plugins want to make use of it.
Does this work for you guys? @dickeyxxx @ransombriggs
=> Add a new color definition for pipelines

lib/command.js, lib/mutex.js, test/command.js, test/mutex.js
@dickeyxxx could you review?  I ended up having to use a mutex around the 2fa prompts because when they are run in parallel they read simultaneously from the same stdin which would cause problems.  I also pushed down the prompt into the promise that is saved per app so that they are only prompted once per app.
The changes from https://github.com/heroku/heroku-cli-util/pull/90 are all in https://github.com/heroku/heroku-cli-util/commit/dee77bf13de05796336d7e14d8544d84d004b828
=> Retry just the request when 2fa / preauth

lib/command.js, test/command.js
Fixes the bug where `heroku login` two factor bombs out because there is no app passed back.
=> Do not try and preauth when no app passed

lib/auth.js, test/auth.js
This change writes a `.netrc` file with Heroku entries that have newline delimiters instead of whitespace delims. For example, this should write:
```
machine api.foo.com
login me@me.com
password mypass
```
Instead of:
```
machine api.foo.com login me@me.com password mypass
```
This resolves a problem in which the [heroku-deploy library](https://github.com/heroku/heroku-maven-plugin/tree/master/heroku-deploy), which is used by a number of command-line Java tools, was unable to read the `.netrc` file. For examples, see [this Stackoverflow post](https://stackoverflow.com/questions/49823912/on-deploy-heroku-says-it-cant-find-api-key-even-though-ive-logged-in/49825623), and this [support ticket](https://support.heroku.com/tickets/572302).
=> Set Heroku netrc entries to have newlines

.circleci/config.yml, package.json, yarn.lock
Bumping this package will bring in the latest changes to `heroku-client` including [a patch](https://github.com/heroku/node-heroku-client/pull/101) that will fix header deprecation warning in node 12.
After merging turn on branch rules for the new node versions
=> chore: update heroku-client & bump ci node versions

lib/table.js, test/table.js
Currently if a table column has a format function that returns null the table output will fail. This pull request will ensure that if a format returns `null` or `undefined` that the resulting value used for the output in the table is an empty string (similar to the default handling of values)
=> fix: handle nullish formats in tables

package.json
We need to change the package name back to the original so that we can publish to npm.
=> chore: change package name back to original

package.json
We're now able to publish new versions of this package, but only under the NPM `@heroku` org.
This PR is just to update the package name inside `package.json` manifest.
=> Update package name to new publisher

.eslintrc.js, examples/run.sh, examples/styled-json-command.ts, examples/styled-object-command.ts, package.json, src/index.ts, src/ux/styled-json.ts, src/ux/styled-object.ts, test/hooks.ts, test/unit/ux/styled-json.test.ts, test/unit/ux/styled-object.test.ts
[W-18294171](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CuR1XYAV/view)
This reimplements `styledObject` and `styledJSON` without using deprecated oclif `ux` functions.
I've added examples to test the ux functions. You can run them and review how they look:
1. npm run example styled-json-command
2. npm run example styled-object-command
=> refactor: reimplement styled object and styled json

.eslintrc.cjs, examples/confirm-command.ts, examples/prompt-command.ts, examples/styled-header-command.ts, examples/styled-json-command.ts, examples/styled-object-command.ts, examples/table-command.ts, package-lock.json, package.json, src/index.ts, src/utils/pg/bastion.ts, src/utils/pg/databases.ts, src/utils/pg/psql.ts, src/ux/prompt.ts, src/ux/wait.ts, test/hooks.ts, test/unit/utils/addons/resolve.test.ts, test/unit/utils/pg/databases.test.ts, test/unit/ux/confirm.test.ts, test/unit/ux/prompt.test.ts, test/unit/ux/styled-header.test.ts, test/unit/ux/styled-json.test.ts, test/unit/ux/styled-object.test.ts, test/unit/ux/table.test.ts, test/unit/ux/wait.test.ts
[W-18293732](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CuL84YAF/view)
[W-18293738](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CuOf7YAF/view)
This reimplements wait and prompt without oclif 2's ux functions. it also uncomments and fixes pg utilities.
1. Pull down branch and `npm run build`
2. `npm run example prompt-command`
=> refactor!: reimplement wait and prompt, add back pg utilities

.mocharc.json, package-lock.json, package.json, src/ux/styled-object.ts, src/ux/table.ts, test/unit/ux/styled-json.test.ts, test/unit/ux/styled-object.test.ts, test/unit/ux/table.test.ts
[W-18575888](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Ek3dFYAR/view)
This changes the `table` function export to have certain defaults (purple column header text, underline border) while also allowing for those defaults (as well as any oclif defaults) to be overridden by passing in options.
1. pull down branch and `npm install`
2. `npm run example table-command`
=> feat: add oclif table options

package-lock.json, src/index.ts
this exposes the DatabaseResolver as part of `utils.pg` so consumers can work directly with the methods on that class.
=> feat: export the DatabaseResolver itself

src/index.ts
This ensures that we can properly type as database connection details.
pull: [heroku-cli-util](https://github.com/heroku/heroku-cli-util)
`git checkout mm/const-to-types-export`
pull heroku-pg-extras
`git checkout command-migrations-oclifv2-set1`
update for local testing:
package.json path for heroku-cli-util:
"@heroku/heroku-cli-util": "file:/Users/michael.malave/Desktop/gitclones/heroku-cli-util",
`git checkout command-migrations-oclifv2-set1`
run the following commands
```
npm install
npm run build
npm test
```
then test some commands
```
bin/run pg:bloat --app $APP
bin/run pg:blocking --app $APP
bin/run pg:cache-hit $DATABASE --app $APP
bin/run pg:calls $DATABASE --app $APP
bin/run pg:extensions $DATABASE --app $APP
```
=> adding export of types and including const for backwards compatibility

package-lock.json, package.json, src/types/pg/tunnel.ts, src/utils/pg/bastion.ts, test/unit/utils/pg/bastion.test.ts
[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002M33k2YAB/view)
This PR upgrades `tunnel-ssh` from `v4.1.6` to `v5.2.0` as part of a plugin installation bug fix. The v5 release had breaking changes with the removal of the v4 default export and its `Config` type while using a promise-based createTunnel() API with built-in types. The `createTunnel` function now requires `tunnelOptions`, `serverOptions`, `sshOptions`, `forwardOptions` parameters. The arguments supplied in the new `createSSHTunnelAdapter()` correspond with the returned object from `tunnelConfig()`.
- Passing CI
=> refactor: update tunnel-ssh for v9
